In [1]:
import tensorflow as tf

In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
mnist = input_data.read_data_sets('MNIST_data/', one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [4]:
mnist.test.images[0].shape

(784,)

In [5]:
from tensorflow.keras.models import Sequential

In [6]:
from tensorflow.keras.layers import Dense, Conv2D, Dropout, MaxPool2D, Reshape

In [7]:
batch_size = 100

In [8]:
mnist.test.images.shape

(10000, 784)

In [9]:
model = Sequential()

model.add(Conv2D(filters=32, kernel_size=(5,5), padding='same', activation='relu', input_shape=(28,28,1)))
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2), padding='same'))

model.add(Conv2D(filters=64, kernel_size=(5,5), padding='same', activation='relu', input_shape=(14,14,32)))
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2), padding='same'))

model.add(Reshape(target_shape=(7*7*64,)))

model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(10, activation='sigmoid'))

model.compile(loss='categorical_crossentropy', optimizer='adam')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 32)        832       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 14, 14, 64)        51264     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
reshape (Reshape)            (None, 3136)              0         
_________________________________________________________________
dense (Dense)                (None, 1024)              3212288   
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0

In [11]:
X_train = mnist.train.images.reshape(-1, 28,28,1)

In [12]:
y_train = mnist.train.labels

In [13]:
y_train.shape

(55000, 10)

In [14]:
X_train.shape

(55000, 28, 28, 1)

In [15]:
model.fit(x=X_train, y=y_train, batch_size=batch_size)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 55000 samples
55000/55000 [==============================] - 29s 523us/sample - loss: 0.1750


In [16]:
X_test = mnist.test.images.reshape(-1, 28, 28, 1)

In [17]:
y_pred = model.predict(X_test)

In [18]:
import numpy as np

In [19]:
labels = np.array([np.argmax(x) for x in mnist.test.labels])

In [20]:
labels

array([7, 2, 1, ..., 4, 5, 6])

In [21]:
predictions = np.array([np.argmax(x) for x in y_pred])

In [22]:
predictions

array([7, 2, 1, ..., 4, 5, 6])

In [23]:
from sklearn.metrics import classification_report, confusion_matrix

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
print(confusion_matrix(labels, predictions))

[[ 974    0    0    0    0    0    2    1    3    0]
 [   0 1125    2    2    0    0    1    2    3    0]
 [   1    0 1022    2    0    0    0    2    5    0]
 [   0    0    0 1005    0    1    0    2    2    0]
 [   0    0    0    0  972    0    0    1    1    8]
 [   1    0    0    9    0  878    1    0    1    2]
 [   6    3    0    1    1    4  937    0    6    0]
 [   0    1    5    2    0    0    0 1015    1    4]
 [   1    0    3    1    0    1    0    1  964    3]
 [   1    1    0    1    3    2    0    3    1  997]]


In [26]:
print(classification_report(labels, predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       1.00      0.99      0.99      1135
           2       0.99      0.99      0.99      1032
           3       0.98      1.00      0.99      1010
           4       1.00      0.99      0.99       982
           5       0.99      0.98      0.99       892
           6       1.00      0.98      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.98      0.99      0.98       974
           9       0.98      0.99      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000



In [27]:
accuracy_score(labels, predictions)

0.9889